<?php

return [
    "Chewy-gooey Caramels" => [
        "Squirrel Nut Caramels",
        "Caramel Squares",
        "Caramel Creams",
        "Caramel Crunch",
        "Caramellos",
        "Tootsie Caramel Apple Pops",
        "Mini Cow Tales",
        "Slap Stix Suckers Caramel",
        "Jelly Belly Caramel Corn",
        "Palmer Bunny Bites Caramel",
        "Wonka Triple Dazzle Caramel Bar",
        "Nips Sugar Free Caramel",
        "Vanilla Caramel",
        "Coffee Rio",
        "Long Boys",
        "Jolly Rancher",
        "Sugar Daddys",
    ],
    "Yummy Gummies" => [
        "Gummi Bears",
        "Gummi Worms",
        "Gummi Cola Bottles",
        "Gummi Cherries",
        "Gummi Fish",
        "Gummi Banana Straberry Ring",
        "Gummi Raspberries",
        "Gum Blow",
        "Fraise Tagada",
        "Gummi Peach Rings",
    ],
    "Tangy Sours" => [
        "Sour Patch Kids",
        "Sour Cherries",
        "Toxic Waste",
        "Sour Punch",
        "Warheads",
        "Sour Plooms",
    ],
    "Strechy-juicy Gums" => [
        "Bazooka Bubble Gum",
        "Beechman’s Gum",
        "Bubble Yum",
        "Wrigley’s Chewing Gum",
        "Ice Breakers",
        "Juicy Fruit",
        "Fruit Stripe Gum",
        "Stride",
    ],
    "Sheer Chocolate" => [
        "Snickers",
        "Twix",
        "Hershey’s Chocolate Bars",
        "Reese’s Peanut Butter Cups",
        "Milk Duds",
        "Milky Way",
        "M&Ms",
        "M&M Peanut Butter",
        "M&M Dark Chocolate",
        "Pretzel M&Ms",
        "Coconut M&Ms",
        "M&M Chocolate Candy",
        "Kit Kat",
        "Krackle",
        "Mars Bars",
        "Skittles",
        "Starbursts",
        "Chocolate Covered Raisins",
        "Chocolate Covered Cherries",
        "Mary Jane",
        "Chocolate Fudge",
        "Almond Cluster",
        "Almond Joy",
        "Baby Ruth",
        "Bar None",
        "Bournville",
        "Butterfinger Crisp",
        "Coconut and Toasted Almond",
        "Cup-o-Gold",
        "Five Star Fruit and Nut",
        "Five Star Hazelnut",
        "Five Star Peanut",
        "Gingembre",
        "GooGoo Cluster",
        "Junior Mints",
        "Idaho Spud",
        "NutRageous",
    ],
];
